version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    working_directory: ~/repo
    steps:

      - checkout
      
      - run:
          name: What's in it?
          command: ls -la

      - run:
          name: Where am I?
          command: pwd

      - run:
          name: Trying change directory
          command: cd ../server
      
      - run: 
          name: Intalling requirements
          command: pip install --no-cache-dir -r requirements.txt

      - run:
          name: Entrypoint permissions
          command: chmod 777 /usr/src/app/entrypoint.sh
      
      - run:
          name: WSGI settings
          command: ./uwsgi.ini /etc/uwsgi.ini

      - run:
          name: Entrypoint execution
          command: ./entrypoint.sh