version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    working_directory: ~/repo
    steps:

      - checkout

      - run: 
          name: Setting environment variable
          command: |
            echo export PYTHONUNBUFFERED=1 >> $BASH_ENV
            echo export FLASK_APP=server/main/__init__.py >> $BASH_ENV
            echo export PYTHONPATH=server >> $BASH_ENV

      - run:
          name: Single pass installation
          command: |
            mkdir -p /usr/src/app
            cd server/
            cp -R . /usr/src/app/
            pip3 install --no-cache-dir -r requirements.txt
            chmod 777 entrypoint.sh
            cp uwsgi.ini /etc/uwsgi.ini
            echo $PYTHONPATH
            ./entrypoint.sh &

      - run:
          name: Testing Flask
          command: |
            echo $PYTHONPATH
            cd server/tests/
            pwd
            python3 base.py
            python3 test_api_routes.py
            python3 test_config.py