version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    working_directory: ~/repo
    steps:

      - checkout

      - run:
          name: Python Dev
          command: apt-get install python3-pip python3-dev
      
      - run:
          name: Trying change directory
          command: |
            cd server/
            pip install --no-cache-dir -r requirements.txt
            chmod 777 entrypoint.sh
            ./uwsgi.ini /etc/uwsgi.ini
            ./entrypoint.sh