version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    steps:

      - run:
          name: Moving into working directory
          command: cd server
      
      - run:
          name: Entrypoint permissions
          command: chmod 777 /usr/src/app/entrypoint.sh
      
      - run: 
          name: Upgrading PIP
          command: pip install --upgrade pip
      
      - run: 
          name: Intalling requirements
          command: pip install --no-cache-dir -r requirements.txt
      
      - run:
          name: WSGI settings
          command: ./uwsgi.ini /etc/uwsgi.ini

      - run:
          name: Entrypoint execution
          command: ./entrypoint.sh