version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    working_directory: ~/repo
    steps:

      - checkout

      - run:
          name: Single pass installation
          command: |
            cd server/
            pip3 install --no-cache-dir -r requirements.txt
            chmod 777 entrypoint.sh
            ./uwsgi.ini /etc/uwsgi.ini
            ./entrypoint.sh