version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    working_directory: ~/repo
    steps:

      - checkout

      - run:
          name: What's in it?
          command: ls -la

      - run:
          name: Trying change directory
          command: |
            cd server/
            pip install --no-cache-dir -r requirements.txt
            chmod 777 /usr/src/app/entrypoint.sh
            ./uwsgi.ini /etc/uwsgi.ini
            ./entrypoint.sh