version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3
    working_directory: ~/repo
    steps:

      - checkout

      - run: 
          name: Setting environment variable
          command: |
            echo export PYTHONUNBUFFERED=1 >> $BASH_ENV
      
      - run:
          name: Retrieve environment variable
          command: echo ${PYTHONUNBUFFERED}

      - run:
          name: Single pass installation
          command: |
            mkdir -p /usr/src/app
            cd server/
            cp -R . /usr/src/app/
            pip3 install --no-cache-dir -r requirements.txt
            chmod 777 entrypoint.sh
            cp uwsgi.ini /etc/uwsgi.ini
            ./entrypoint.sh